### ISSUE TITLE
Virtual Coordinate

### ISSUE THREAD

**Issue by kittyBS** [charly1469/LincOFinder#2]
Hello,
First of all, I would like to thank you for your tool and the article. When creating the input, how should the 'virtual coordinate' be generated? If I need to quote from your article, I thought it should be something like 'the first gene in chromosome A will be chrA-1, the second chrA-2,' as you mentioned, but it doesn't seem to be the case in the provided example. How can I create an appropriate 'virtual coordinate'?

**Comment by cherrera1990** [comment]
Hi, in the two files provided in the example from Human

**Comment by cherrera1990** [comment]
Hi! 
In the two files provided in the example for Human "File_int_species_Hsa"
`1	ensembl_havana	gene	65419	71585	.	+	.	gene_id "ENSG00000186092"; gene_version "6"; gene_name "OR4F5"; gene_source "ensembl_havana"; gene_biotype "protein_coding";`
`1	ensembl_havana	gene	450703	451697	.	-	.	gene_id "ENSG00000284733"; gene_version "1"; gene_name "OR4F29"; gene_source "ensembl_havana"; gene_biotype "protein_coding";`

and amphioxus "File_ref_species_Bla"
`Sc0000000,25509,29694,BL09450,BL09450_cuf0,+,coding
Sc0000000,283302,326093,BL10006,BL10006_cuf7,+,coding
Sc0000000,372950,374384,BL73495,BL73495_cuf0,+,coding`

Genes are already sorted within each chromosome in the case of human and scaffold in the case of amphioxus. The two genes showed in here for human would be chr1-1 and chr1-2 and in the case of amphioxus the 3 genes showed would be Sc000000-1, Sc000000-2 and Sc000000-3. Once sorted, the gene_id and position within chromosome is stored and used to generate the Example_find_synteny_input.txt. As you can see, BL09450 (Sc000000-1) is showed here without orthologies, followed by BL10006 (Sc000000-2) and BL73495 (Sc000000-3) with all their orthologs and their position, chromosome and strand. Finally we have BL60128 (Sc000000-4)which is a lncRNA. 
`BL09450`
`BL10006	ENSG00000111319|52|12|-	ENSG00000072182|1080|2|+	ENSG00000166828|314|16|+	ENSG00000168447|315|16|+	ENSG00000108684|432|17|-	ENSG00000110881|383|12|+	ENSG00000213199|877|7|+`
`BL73495	ENSG00000147789|680|8|+	ENSG00000197050|759|19|+	ENSG00000180787|106|17|+	ENSG00000124613|171|6|+	ENSG00000184635|606|19|+	ENSG00000130844|1287|19|+	ENSG00000198453|758|19|+	ENSG00000063587|775|0|+	ENSG00000254004|749|19|-	ENSG00000250312|2|4|+	ENSG00000183850|633|19|+	ENSG00000272602|1|4|+	ENSG00000167635|745|19|+	ENSG00000189190|1263|19|-	ENSG00000185177|295|7|-	ENSG00000182111|296|7|+	ENSG00000196081|634|19|-	ENSG00000256771|605|19|+	ENSG00000237440|610|19|-	ENSG00000188171|611|19|-	ENSG00000142065|746|19|-	ENSG00000251247|756|19|+	ENSG00000196605|288|19|-	ENSG00000160229|612|19|+	ENSG00000196150|682|8|-	ENSG00000125945|301|1|-	ENSG00000197372|637|19|-	ENSG00000221923|1255|19|+	ENSG00000167766|1261|19|-	ENSG00000198939|851|5|+	ENSG00000179195|991|12|+	ENSG00000127903|1398|19|-	ENSG00000197134|625|19|+	ENSG00000147117|193|0|+	ENSG00000197360|628|19|-	ENSG00000181450|1882|1|+	ENSG00000197951|1396|19|+	ENSG00000196418|1995|1|-	ENSG00000277462|1993|1|-	ENSG00000176293|1450|19|+	ENSG00000229676|629|19|+	ENSG00000196437|766|19|-	ENSG00000173041|302|7|-	ENSG00000223614|299|7|+	ENSG00000234284|854|5|+	ENSG00000175395|154|10|-	ENSG00000197013|621|19|+	ENSG00000083828|1437|19|+	ENSG00000198393|1029|12|+	ENSG00000131127|4|4|+	ENSG00000160352|615|19|+	ENSG00000197020|622|19|-	ENSG00000182141|617|19|-`
`BL60128	Hypnc_BL60128`

So, to answer your question, you can either used the formatting described in "preparation_README.md" alongside the preparation_input_tool.pl or you can generate your input file with the format described in "README.md" 

Ref_GeneID Ortholog1(Int_GeneID|virtual_coordinate|Chromosome|strand) Ortholog2 Ortholog3...OrthologN for coding genes
Ref_GeneID "Hypnc_"Name_of_the_lincRNA for lincRNAs

I hope I have been able to help!

**Comment by kittyBS** [comment]
Thank you for your quick and informative response!
Best regards
